### ISSUE TITLE
oroconf extract is broken

### ISSUE THREAD

**Issue by goldhoorn** [rock-core/tools-orocosrb#70]
See error:
```
[16:08:57 goldhoorn orocos.rb]$ oroconf extract sonar_tritech::Micron 
Bundles[INFO]: No bundle currently selected
orocos.rb[WARN]: killing running task contexts and deployments because of unhandled exception
orocos.rb[WARN]:   /home/goldhoorn/dev-avalon-21/tools/orocos.rb/bin/oroconf:89:in `dump_configuration': undefined method `config_as_hash' for Orocos::TaskConfigurations:Class
orocos.rb[WARN]:     /home/goldhoorn/dev-avalon-21/tools/orocos.rb/bin/oroconf:106:in `block in <main>'
orocos.rb[WARN]:     /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/process.rb:695:in `block in run'
orocos.rb[WARN]:     /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/process.rb:1098:in `guard'
orocos.rb[WARN]:     /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/process.rb:694:in `run'
orocos.rb[WARN]:     /home/goldhoorn/dev-avalon-21/tools/orocos.rb/lib/orocos/process.rb:107:in `run'
orocos.rb[WARN]:     /home/goldhoorn/dev-avalon-21/tools/orocos.rb/bin/oroconf:104:in `<main>'
```

**Comment by goldhoorn** [comment]
@saarnold @jakobs : could you fix this, your are team 8 responsible for this package (besides the maintainer itself)

**Comment by doudou** [comment]
FYI, --save works

**Comment by doudou** [comment]
Could you test #78 ?

**Comment by goldhoorn** [comment]
works, thanks....
